version: '3.8'

services:
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
      target: frankenphp_dev
    privileged: true
    restart: on-failure
    environment:
      - APP_SECRET=changeme
    volumes:
      - ./:/app
    tty: true
    ports:
      - "8888:80"
